version: "3.3"

services:
  zomboid-dedicated-server:
    build:
      context: .
      dockerfile: docker/zomboid-dedicated-server.Dockerfile
    image: "docker.io/renegademaster/zomboid-dedicated-server:latest"
    container_name: zomboid-dedicated-server
    restart: "no"
    environment:
      - "ADMIN_PASSWORD=919712"
      - "ADMIN_USERNAME=bangurion"
      - "AUTOSAVE_INTERVAL=15"
      - "BIND_IP=0.0.0.0"
      - "GAME_PORT=8766"
      - "GAME_VERSION=public"
      - "MAP_NAMES=Muldraugh, KY"
      - "MAX_PLAYERS=10"
      - "MAX_RAM=6144m"
      - "MOD_NAMES="
      - "MOD_WORKSHOP_IDS="
      - "PAUSE_ON_EMPTY=true"
      - "PUBLIC_SERVER=true"
      - "QUERY_PORT=16261"
      - "RCON_PASSWORD=changeme_rcon"
      - "RCON_PORT=27015"
      - "SERVER_NAME=Machado99"
      - "SERVER_PASSWORD="
      - "STEAM_VAC=true"
      - "USE_STEAM=true"
    ports:
      - target: 8766
        published: 8766
        protocol: udp
      - target: 16261
        published: 16261
        protocol: udp
      - target: 27015
        published: 27015
        protocol: tcp
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ./ZomboidConfig:/home/steam/Zomboid/
