SandboxVars = {
    VERSION = 4,
    -- Alterar essa configuração definirá a opção avançada "Multiplicador de População". Padrão=Normal
    -- 1 = Insano
    -- 2 = Muito Alto
    -- 3 = Alto
    -- 4 = Normal
    -- 5 = Baixo
    Zombies = 4,
    -- Padrão=Foco Urbano
    -- 1 = Foco Urbano
    Distribution = 1,
    -- Padrão=1 Hora
    -- 1 = 15 Minutos
    -- 2 = 30 Minutos
    -- 3 = 1 Hora
    -- 4 = 2 Horas
    -- 5 = 3 Horas
    -- 6 = 4 Horas
    -- 7 = 5 Horas
    -- 8 = 6 Horas
    -- 9 = 7 Horas
    -- 10 = 8 Horas
    -- 11 = 9 Horas
    -- 12 = 10 Horas
    -- 13 = 11 Horas
    -- 14 = 12 Horas
    -- 15 = 13 Horas
    -- 16 = 14 Horas
    -- 17 = 15 Horas
    -- 18 = 16 Horas
    -- 19 = 17 Horas
    -- 20 = 18 Horas
    -- 21 = 19 Horas
    -- 22 = 20 Horas
    -- 23 = 21 Horas
    -- 24 = 22 Horas
    -- 25 = 23 Horas
    DayLength = 3,
    StartYear = 1,
    -- Padrão=Julho
    -- 1 = Janeiro
    -- 2 = Fevereiro
    -- 3 = Março
    -- 4 = Abril
    -- 5 = Maio
    -- 6 = Junho
    -- 7 = Julho
    -- 8 = Agosto
    -- 9 = Setembro
    -- 10 = Outubro
    -- 11 = Novembro
    StartMonth = 7,
    StartDay = 9,
    -- Padrão=09:00
    -- 1 = 07:00
    -- 2 = 09:00
    -- 3 = 12:00
    -- 4 = 14:00
    -- 5 = 17:00
    -- 6 = 19:00
    -- 7 = 00:00
    -- 8 = 02:00
    StartTime = 2,
    -- Padrão=0-30 Dias
    -- 1 = Instantâneo
    -- 2 = 0-30 Dias
    -- 3 = 0-2 Meses
    -- 4 = 0-6 Meses
    -- 5 = 0-1 Ano
    -- 6 = 0-5 Anos
    -- 7 = 2-6 Meses
    WaterShut = 2,
    -- Padrão=0-30 Dias
    -- 1 = Instantâneo
    -- 2 = 0-30 Dias
    -- 3 = 0-2 Meses
    -- 4 = 0-6 Meses
    -- 5 = 0-1 Ano
    -- 6 = 0-5 Anos
    -- 7 = 2-6 Meses
    ElecShut = 2,
    -- Mínimo=-1 Máximo=2147483647 Padrão=14
    WaterShutModifier = 14,
    -- Mínimo=-1 Máximo=2147483647 Padrão=14
    ElecShutModifier = 14,
    -- Padrão=Raro
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Normal
    -- 4 = Comum
    FoodLoot = 2,
    -- Padrão=Raro
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Normal
    -- 4 = Comum
    CannedFoodLoot = 2,
    -- Padrão=Raro
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Normal
    -- 4 = Comum
    LiteratureLoot = 2,
    -- Sementes, Pregos, Serras, Varas de Pesca, Ferramentas, etc... Padrão=Raro
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Normal
    -- 4 = Comum
    SurvivalGearsLoot = 2,
    -- Padrão=Raro
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Normal
    -- 4 = Comum
    MedicalLoot = 2,
    -- Padrão=Raro
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Normal
    -- 4 = Comum
    WeaponLoot = 3,
    -- Padrão=Raro
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Normal
    -- 4 = Comum
    RangedWeaponLoot = 3,
    -- Padrão=Raro
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Normal
    -- 4 = Comum
    AmmoLoot = 2,
    -- Padrão=Raro
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Normal
    -- 4 = Comum
    MechanicsLoot = 2,
    -- Padrão=Raro
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Normal
    -- 4 = Comum
    OtherLoot = 2,
    -- Controla a condição global da temperatura. Padrão=Normal
    -- 1 = Muito Frio
    -- 2 = Frio
    -- 3 = Normal
    -- 4 = Quente
    Temperature = 3,
    -- Controla a frequência com que ocorrerá chuvas e tempestades. Padrão=Normal
    -- 1 = Bem Seco
    -- 2 = Seco
    -- 3 = Normal
    -- 4 = Chuvoso
    Rain = 3,
    -- Número de dias até que a natureza esteja completamente desenvolvida. Padrão=Normal (100 Dias)
    -- 1 = Muito Rápido (20 Dias)
    -- 2 = Rápido (50 Dias)
    -- 3 = Normal (100 Dias)
    -- 4 = Lento (200 Dias)
    ErosionSpeed = 3,
    -- Número de dias até que a natureza esteja completamente desenvolvida. -1 significa nunca crescer. Zero significa usar a opção "Velocidade da Erosão". Máximo 36,500 (100 anos). Mínimo=-1 Máximo=36500 Padrão=0
    ErosionDays = 0,
    -- Modifica o ganho base de XP das ações multiplicadas por esse número. Mínimo=0,00 Máximo=1000,00 Padrão=1,00
    XpMultiplier = 1000.0,
    -- Aumenta ou reduz o multiplicador de intensidade do som do motor em geral. Mínimo=0,00 Máximo=100,00 Padrão=1,00
    ZombieAttractionMultiplier = 1.0,
    -- Controla se os veículos estarão trancados ou não, precisarão de chaves para ignição, etc.
    VehicleEasyUse = false,
    -- Controla a velocidade de crescimento da plantação. Padrão=Normal
    -- 1 = Muito Rápido
    -- 2 = Rápido
    -- 3 = Normal
    -- 4 = Lento
    Farming = 1,
    -- Controla o tempo que leva para o alimento se decompor em uma composteira. Padrão=2 Semanas
    -- 1 = 1 Semana
    -- 2 = 2 Semanas
    -- 3 = 3 Semanas
    -- 4 = 4 Semanas
    -- 5 = 6 Semanas
    -- 6 = 8 Semanas
    -- 7 = 10 Semanas
    CompostTime = 1,
    -- Define o quão rápido a fome, a sede e a fadiga do personagem irão decair. Padrão=Normal
    -- 1 = Muito Rápido
    -- 2 = Rápido
    -- 3 = Normal
    -- 4 = Lento
    StatsDecrease = 3,
    -- Controla a abundância da pesca e de recursos de coleta, em geral. Padrão=Normal
    -- 1 = Muito Ruim
    -- 2 = Ruim
    -- 3 = Normal
    -- 4 = Abundante
    NatureAbundance = 3,
    -- Padrão=Algumas Vezes
    -- 1 = Nunca
    -- 2 = Extremamente Raro
    -- 3 = Raro
    -- 4 = Algumas Vezes
    -- 5 = Frequentemente
    Alarm = 4,
    -- Define com que frequência as casas e construções recém-descobertas estarão trancadas. Padrão=Muito Frequentemente
    -- 1 = Nunca
    -- 2 = Extremamente Raro
    -- 3 = Raro
    -- 4 = Algumas Vezes
    -- 5 = Frequentemente
    LockedHouses = 6,
    -- Inicia com salgadinho, garrafa de água, mochila escolar, taco de beisebol e um martelo em seu inventário.
    StarterKit = true,
    -- O valor nutricional dos alimentos afetarão a condição do jogador.
    Nutrition = true,
    -- Define o quão rápido os alimentos irão estragar dentro ou fora da geladeira. Padrão=Normal
    -- 1 = Muito Rápido
    -- 2 = Rápido
    -- 3 = Normal
    -- 4 = Devagar
    FoodRotSpeed = 3,
    -- Define o nível de eficiência da geladeira. Padrão=Normal
    -- 1 = Muito Baixo
    -- 2 = Baixo
    -- 3 = Normal
    -- 4 = Alto
    FridgeFactor = 3,
    -- Itens ressurgirão em recipientes já looteados nas cidades e vizinhanças. Os itens não reaparecerão em recipientes criados pelo jogador. Padrão=Nenhum
    -- 1 = Nenhum
    -- 2 = Todos os Dias
    -- 3 = Uma Vez por Semana
    -- 4 = Uma Vez por Mês
    LootRespawn = 1,
    -- Se acima de 0, os itens não ressurgirão nos recipientes que foram looteados dentro desse tempo em horas de jogo. Mínimo=0 Máximo=2147483647 Padrão=0
    SeenHoursPreventLootRespawn = 0,
    -- Lista de itens, separados por vírgula, que serão removidos após o tempo definido em "Horas para Remover Itens na Lista".
    WorldItemRemovalList = "Base.Vest,Base.Shirt,Base.Blouse,Base.Skirt,Base.Shoes,Base.Hat,Base.Glasses,Base.Maggots,Base.Maggots2",
    -- Número em horas antes do item ser removido, contado a partir do momento em que é colocado no chão. Os itens são removidos assim que a área do mapa é carregada. Quando zero, estes não serão removidos. Mínimo=0,00 Máximo=2147483647,00 Padrão=24,00
    HoursForWorldItemRemoval = 24.0,
    -- Se marcado, os itens que *não* estiverem na lista serão removidos.
    ItemRemovalListBlacklistToggle = false,
    -- Isso afetará o início da erosão do mundo e a validade dos alimentos. Padrão=0
    -- 1 = 0
    -- 2 = 1
    -- 3 = 2
    -- 4 = 3
    -- 5 = 4
    -- 6 = 5
    -- 7 = 6
    -- 8 = 7
    -- 9 = 8
    -- 10 = 9
    -- 11 = 10
    -- 12 = 11
    TimeSinceApo = 1,
    -- Influencia na quantidade de água que a planta precisa por dia e a capacidade de evitar pragas. Padrão=Normal
    -- 1 = Muito Alto
    -- 2 = Alto
    -- 3 = Normal
    -- 4 = Baixo
    PlantResilience = 1,
    -- Influenciará na quantidade de vegetais que uma planta produzirá. Padrão=Normal
    -- 1 = Muito Ruim
    -- 2 = Ruim
    -- 3 = Normal
    -- 4 = Abundante
    PlantAbundance = 5,
    -- Tempo de recuperação do cansaço causado por diversas ações. Padrão=Normal
    -- 1 = Muito Rápido
    -- 2 = Rápido
    -- 3 = Normal
    -- 4 = Lento
    EndRegen = 3,
    -- Frequência com que helicópteros aparecerão na área. Padrão=Uma Vez
    -- 1 = Nunca
    -- 2 = Uma Vez
    -- 3 = Algumas Vezes
    Helicopter = 1,
    -- Frequência com que eventos que atraem zumbis ocorrerão, como por exemplo som de tiros. Padrão=Algumas Vezes
    -- 1 = Nunca
    -- 2 = Algumas Vezes
    MetaEvent = 2,
    -- Controla os eventos que ocorrerão enquanto o jogador estiver dormindo. Padrão=Nunca
    -- 1 = Nunca
    -- 2 = Algumas Vezes
    SleepingEvent = 1,
    -- Aumenta/Reduz a chance de geradores elétricos aparecerem no mapa. Padrão=Algumas Vezes
    -- 1 = Extremamente Raro
    -- 2 = Raro
    -- 3 = Algumas Vezes
    -- 4 = Frequentemente
    GeneratorSpawning = 3,
    -- Quanto consumirá de combustível a cada hora de jogo. Mínimo=0,00 Máximo=100,00 Padrão=1,00
    GeneratorFuelConsumption = 1.0,
    -- Aumenta/Diminui a probabilidade de descobrir refúgios aleatórios pelo mapa: lugares queimados, com diversos itens, sobreviventes mortos, etc. Padrão=Raro
    -- 1 = Nunca
    -- 2 = Extremamente Raro
    -- 3 = Raro
    -- 4 = Algumas Vezes
    -- 5 = Frequentemente
    SurvivorHouseChance = 3,
    -- Padrão=Raro
    -- 1 = Nunca
    -- 2 = Extremamente Raro
    -- 3 = Raro
    -- 4 = Algumas Vezes
    -- 5 = Frequentemente
    VehicleStoryChance = 3,
    -- Padrão=Raro
    -- 1 = Nunca
    -- 2 = Extremamente Raro
    -- 3 = Raro
    -- 4 = Algumas Vezes
    -- 5 = Frequentemente
    ZoneStoryChance = 3,
    -- Influencia na chance que um mapa encontrado haverá anotações deixadas por um sobrevivente. Padrão=Algumas Vezes
    -- 1 = Nunca
    -- 2 = Extremamente Raro
    -- 3 = Raro
    -- 4 = Algumas Vezes
    -- 5 = Frequentemente
    AnnotatedMapChance = 4,
    -- Adiciona pontos extras de traços para serem usados durante a criação do personagem. Mínimo=-100 Máximo=100 Padrão=0
    CharacterFreePoints = 100,
    -- Adiciona resistência extra, contra dano de zumbis, nas construções feitas por jogadores. Padrão=Normal
    -- 1 = Muito Baixo
    -- 2 = Baixo
    -- 3 = Normal
    -- 4 = Alto
    ConstructionBonusPoints = 3,
    -- Controla a luminosidade do mapa durante a noite. Padrão=Normal
    -- 1 = Completamente Escuro
    -- 2 = Escuro
    -- 3 = Normal
    NightDarkness = 3,
    -- Define quanto tempo levará para alternar da noite para o dia. Padrão=Normal
    -- 1 = Sempre Noite
    -- 2 = Longo
    -- 3 = Normal
    -- 4 = Curto
    NightLength = 3,
    -- Aumenta ou diminui o impacto das lesões que acontecem em seu corpo, assim como seu tempo de cura. Padrão=Normal
    -- 1 = Baixo
    -- 2 = Normal
    InjurySeverity = 2,
    -- Ativa ou desativa a chance de fraturas em partes do corpo quando o sobrevivente recebe impactos fortes, danos de zumbis e quedas.
    BoneFracture = true,
    -- Quanto tempo levará para que cadáveres de zumbis desapareçam. Mínimo=-1,00 Máximo=2147483647,00 Padrão=216,00
    HoursForCorpseRemoval = 216.0,
    -- Controla o impacto que cadáveres em decomposição próximos ao jogador causem efeitos na saúde e humor. Padrão=Normal
    -- 1 = Nenhum
    -- 2 = Baixo
    -- 3 = Normal
    DecayingCorpseHealthImpact = 3,
    -- Quantidade de sangue será derramado no chão e paredes. Padrão=Normal
    -- 1 = Nenhum
    -- 2 = Baixo
    -- 3 = Normal
    -- 4 = Alto
    BloodLevel = 3,
    -- Define a velocidade em que as roupas se degradarão, ficar sujas e ensanguentadas. Padrão=Normal
    -- 1 = Desabilitado
    -- 2 = Devagar
    -- 3 = Normal
    ClothingDegradation = 3,
    FireSpread = true,
    -- Número de dias de jogo para que o alimento podre seja removido do mapa. -1 significa que nunca serão removidos. Mínimo=-1 Máximo=2147483647 Padrão=-1
    DaysForRottenFoodRemoval = -1,
    -- Se habilitado, geradores irão funcionar no lado de fora das construções permitindo que, por exemplo, energizem as bombas de combustíveis.
    AllowExteriorGenerator = true,
    -- Controla a intensidade máxima da neblina. Padrão=Normal
    -- 1 = Normal
    -- 2 = Moderado
    MaxFogIntensity = 1,
    -- Controla a intensidade máxima da chuva. Padrão=Normal
    -- 1 = Normal
    -- 2 = Moderado
    MaxRainFxIntensity = 1,
    -- Se desabilitado, a neve não acumulará no chão mas ainda ficará visível em vegetações e telhados.
    EnableSnowOnGround = true,
    -- Quando habilitado, certas armas brancas poderão atingir diversos zumbis em um único acerto.
    MultiHitZombies = false,
    -- Chance de ser mordido quando um zumbi atacar pelas costas. Padrão=Alto
    -- 1 = Baixo
    -- 2 = Médio
    RearVulnerability = 3,
    -- Impede de andar enquanto ataca corpo a corpo.
    AttackBlockMovements = true,
    AllClothesUnlocked = false,
    -- Controla a frequência com que veículos surgem no mapa Padrão=Baixo
    -- 1 = Nenhum
    -- 2 = Muito Baixo
    -- 3 = Baixo
    -- 4 = Normal
    CarSpawnRate = 3,
    -- Controla as chances de encontrar um carro com gasolina no tanque. Padrão=Baixo
    -- 1 = Baixo
    -- 2 = Normal
    ChanceHasGas = 1,
    -- Controla quanta gasolina haverá em carros recém-descobertos. Padrão=Baixo
    -- 1 = Muito Baixo
    -- 2 = Baixo
    -- 3 = Normal
    -- 4 = Alto
    -- 5 = Muito Alto
    InitialGas = 2,
    -- Controla a quantidade de gasolina inicial nos postos de combustível. Padrão=Normal
    -- 1 = Vazio
    -- 2 = Muito Baixo
    -- 3 = Baixo
    -- 4 = Normal
    -- 5 = Alto
    -- 6 = Muito Alto
    -- 7 = Cheio
    FuelStationGas = 4,
    -- Quanto de gasolina os veículos consumirão. Mínimo=0,00 Máximo=100,00 Padrão=1,00
    CarGasConsumption = 1.0,
    -- Padrão=Raro
    -- 1 = Nunca
    -- 2 = Extremamente Raro
    -- 3 = Raro
    -- 4 = Algumas Vezes
    -- 5 = Frequentemente
    LockedCar = 3,
    -- Condição geral dos veículos descobertos no mapa. Padrão=Baixo
    -- 1 = Muito Baixo
    -- 2 = Baixo
    -- 3 = Normal
    -- 4 = Alto
    CarGeneralCondition = 2,
    -- Controla a quantidade de danos causados nos veículos em uma batida. Padrão=Normal
    -- 1 = Muito Baixo
    -- 2 = Baixo
    -- 3 = Normal
    -- 4 = Alto
    CarDamageOnImpact = 3,
    -- Dano recebido pelo jogador ao ser atropelado por um carro. Padrão=Nenhum
    -- 1 = Nenhum
    -- 2 = Baixo
    -- 3 = Normal
    -- 4 = Alto
    DamageToPlayerFromHitByACar = 1,
    -- Habilita ou desabilita o surgimento de congestionamento de carros nas estradas principais do mapa.
    TrafficJam = true,
    -- Frequência com que carros serão encontrados com alarme. Padrão=Extremamente Raro
    -- 1 = Nunca
    -- 2 = Extremamente Raro
    -- 3 = Raro
    -- 4 = Algumas Vezes
    -- 5 = Frequentemente
    CarAlarm = 2,
    -- Habilita ou desabilita danos que jogadores sofrem de um carro em um acidente.
    PlayerDamageFromCrash = true,
    -- Quantas horas, em jogo, uma sirene ficará tocando antes de desligar automaticamente. Mínimo=0,00 Máximo=168,00 Padrão=0,00
    SirenShutoffHours = 0.0,
    -- Permite que o jogador encontre um carro de sobrevivente que foi bem conservado depois da pandemia. Padrão=Baixo
    -- 1 = Baixo
    -- 2 = Normal
    RecentlySurvivorVehicles = 1,
    -- Permite o spawn de veículos.
    EnableVehicles = true,
    Map = {
        AllowMiniMap = true,
        AllowWorldMap = true,
        MapAllKnown = true,
    },
    ZombieLore = {
        -- Controla a taxa de movimentação do zumbi. Padrão=Normal
        -- 1 = Corredores (Sprinters)
        -- 2 = Normal
        -- 3 = Lento
        Speed = 2,
        -- Controla o dano de cada ataque causado pelos zumbis. Padrão=Normal
        -- 1 = Super-humano
        -- 2 = Normal
        -- 3 = Fraco
        Strength = 2,
        -- Controla a dificuldade de matar zumbis. Padrão=Normal
        -- 1 = Resistente
        -- 2 = Normal
        -- 3 = Frágil
        Toughness = 2,
        -- Controla como o vírus é espalhado. Padrão=Sangue + Saliva
        -- 1 = Sangue + Saliva
        -- 2 = Apenas Saliva
        -- 3 = Todos estão Infectados
        Transmission = 1,
        -- Controla o tempo de início do desenvolvimento da zumbificação. Padrão=2-3 Dias
        -- 1 = Instantâneo
        -- 2 = 0-30 Segundos
        -- 3 = 0-1 Minutos
        -- 4 = 0-12 Horas
        -- 5 = 2-3 Dias
        -- 6 = 1-2 Semanas
        Mortality = 5,
        -- Controla quando os corpos zumbificados renascerão como zumbis. Padrão=0-1 Minutos
        -- 1 = Instantâneo
        -- 2 = 0-30 Segundos
        -- 3 = 0-1 Minutos
        -- 4 = 0-12 Horas
        -- 5 = 2-3 Dias
        Reanimate = 3,
        -- Controla a inteligência do zumbi. Padrão=Básico
        -- 1 = Avançado (Usa Portas)
        -- 2 = Normal
        -- 3 = Básico
        Cognition = 3,
        -- Controla se os zumbis podem se rastejar por debaixo de veículos. Padrão=Frequentemente
        -- 1 = Apenas Rastejantes
        -- 2 = Extremamente Raro
        -- 3 = Raro
        -- 4 = Algumas Vezes
        -- 5 = Frequentemente
        -- 6 = Muito Frequentemente
        CrawlUnderVehicle = 5,
        -- Controla o tempo em que os zumbis se lembrarão de jogadores após vê-los ou ouvi-los. Padrão=Normal
        -- 1 = Longo
        -- 2 = Normal
        -- 3 = Curto
        Memory = 2,
        -- Controla os efeitos da decomposição com o passar do tempo. Padrão=Lenta + Debilitante
        -- 1 = Lenta + Debilitante
        -- 2 = Lenta
        -- 3 = Debilitante
        Decomp = 1,
        -- Controla a distância da visão do zumbi. Padrão=Normal
        -- 1 = Olhos de Águia
        -- 2 = Normal
        Sight = 2,
        -- Controla a distância da audição do zumbi. Padrão=Normal
        -- 1 = Alta
        -- 2 = Normal
        Hearing = 2,
        -- Zumbis que não viram ou escutaram jogadores poderão atacar portas e construções enquanto vagam.
        ThumpNoChasing = false,
        -- Define se zumbis poderão ou não destruir construções e cercas feitas pelo jogador.
        ThumpOnConstruction = true,
        -- Define se os zumbis serão mais ativos durante o dia, ou à noite.  Zumbis ativos usarão a velocidade definida na configuração "Velocidade". Zumbis inativos serão mais lentos e não tendem a perseguir o jogador. Padrão=Ambos
        -- 1 = Ambos
        -- 2 = Noite
        ActiveOnly = 1,
        -- Permite que zumbis ativem alarmes de casas quando entrarem através de janelas e portas.
        TriggerHouseAlarm = false,
        -- Se ativo, quando múltiplos zumbis estiverem atacando, estes poderão derrubar você no chão para te devorar. Depende da força do zumbi.
        ZombiesDragDown = true,
        -- Se habilitado, zumbis poderão se jogar através da cerca, quando muito perto de você.
        ZombiesFenceLunge = true,
    },
    ZombieConfig = {
        -- Definido pela opção de população "Quantidade de Zumbis". 4.0 = Insano, Muito Alto = 3.0, 2.0 = Alto, 1.0 = Normal, 0.35 = Baixo, 0.0 = Nenhum. Mínimo=0,00 Máximo=4,00 Padrão=1,00
        PopulationMultiplier = 1.0,
        -- Ajusta a população do início do jogo. Mínimo=0,00 Máximo=4,00 Padrão=1,00
        PopulationStartMultiplier = 1.0,
        -- Ajusta a população no dia de pico. Mínimo=0,00 Máximo=4,00 Padrão=1,50
        PopulationPeakMultiplier = 1.5,
        -- Dia em que a população alcançará seu pico. Mínimo=1 Máximo=365 Padrão=28
        PopulationPeakDay = 28,
        -- Horas necessárias para passar por uma área antes que os zumbis reaparaceçam nessa região. Se for 0, não haverá respawn. Mínimo=0,00 Máximo=8760,00 Padrão=72,00
        RespawnHours = 144.0,
        -- Horas em que uma área precisa deixar de ser visitada antes que os zumbis possam reaparacer nela. Mínimo=0,00 Máximo=8760,00 Padrão=16,00
        RespawnUnseenHours = 16.0,
        -- Fração de população desejada de uma região que reaparecerá de acordo com a configuração "Horas de Respawn". Mínimo=0,00 Máximo=1,00 Padrão=0,10
        RespawnMultiplier = 0.1,
        -- Horas necessárias para passar por uma área antes que os zumbis migrem para partes vazias de uma região. Se 0, a migração não acontecerá. Mínimo=0,00 Máximo=8760,00 Padrão=12,00
        RedistributeHours = 12.0,
        -- Distância em que um zumbi tentará percorrer até o local que escutou um som. Mínimo=10 Máximo=1000 Padrão=100
        FollowSoundDistance = 100,
        -- Tamanho máximo das hordas que serão formadas quando os zumbis estiverem ociosos. Se for 0, significa que zumbis não formam hordas.\Hordas não se formam dentro de construções ou áreas de florestas. Mínimo=0 Máximo=1000 Padrão=20
        RallyGroupSize = 20,
        -- Distância máxima que os zumbis percorrerão para formar hordas quando ociosos. Mínimo=5 Máximo=50 Padrão=20
        RallyTravelDistance = 20,
        -- Distância entre hordas. Mínimo=5 Máximo=25 Padrão=15
        RallyGroupSeparation = 15,
        -- O quão próximo os membros de uma horda estarão de seu líder. Mínimo=1 Máximo=10 Padrão=3
        RallyGroupRadius = 3,
    },
    sts = {
        -- If set to 10 then 10 days will be simulated in each month (120 day years). Skipping 2 days for every 1 day played. Recommended setting 2+ hour days if setting a value less than 10 days. Erosion, farming, etc. will only account for days played (not skipped, 120 days in this case) Mínimo=1,00 Máximo=15,00 Padrão=10,00
        MaxDaysInMonth = 10.0,
    },
    VehicleRecycling = {
        -- The following parts must be uninstalled before dismantling: hood, trunk lid, doors, windows, seats.
        UninstallParts = false,
        -- Mínimo=1 Máximo=100 Padrão=1
        ActionTimeMultiplier = 5,
    },
}
